Resources:
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ${self:service}-${self:custom.stage}
      Description: API Gateway instance
  GatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_4XX
      RestApiId:
        Ref: "ApiGatewayRestApi"
  GatewayResponseDefault5XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_5XX
      RestApiId:
        Ref: "ApiGatewayRestApi"
Outputs:
  RestApiId:
    Value:
      Ref: ApiGatewayRestApi
    Export:
      Name: ${self:service}-${self:custom.stage}-RestApiId
  RootResourceId:
    Value:
      Fn::GetAtt: ApiGatewayRestApi.RootResourceId
    Export:
      Name: ${self:service}-${self:custom.stage}-RootResourceId
